name: favorite_places_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_riverpod: ^2.6.1
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  location: ^8.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
